In [1]:
import pandas as pd

In [3]:
import numpy as np

In [33]:
students = pd.DataFrame({
    "student_id": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    "name": ["Abel", "Sara", None, "John", "Marta", None, "David", "Helen", "Tom", None],
    "department": ["CS", "IT", "CS", None, "SE", "IT", "SE", None, "CS", "IT"],
    "gpa": [3.5, 3.8, np.nan, 2.9, 3.7, np.nan, 3.2, 3.4, 3.9, np.nan],
    "scholarship": [5000, np.nan, 3000, 2000, np.nan, 4000, 3500, np.nan, 5000, np.nan]
})
students

   student_id   name department  gpa  scholarship
0         201   Abel         CS  3.5       5000.0
1         202   Sara         IT  3.8          NaN
2         203   None         CS  NaN       3000.0
3         204   John       None  2.9       2000.0
4         205  Marta         SE  3.7          NaN
5         206   None         IT  NaN       4000.0
6         207  David         SE  3.2       3500.0
7         208  Helen       None  3.4          NaN
8         209    Tom         CS  3.9       5000.0
9         210   None         IT  NaN          NaN

In [5]:
##Count missing values
print(students.isnull().sum())

student_id     0
name           3
department     2
gpa            3
scholarship    4
dtype: int64

In [7]:
##Calculate missing-value percentages
print((students.isnull().sum() / len(students)) * 100)

student_id      0.0
name           30.0
department     20.0
gpa            30.0
scholarship    40.0
dtype: float64

In [42]:
##Replace missing names with "Unknown"
students['name'] = students['name'].fillna("Unknown")
students

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     John       None  2.9       2000.0
4         205    Marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen       None  3.4          0.0
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0

In [45]:
##Replace missing departments using mode
students["department"] = students["department"].fillna(students["department"].mode()[0])
students

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          0.0
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0

In [56]:
##Replace missing GPA values using median
students["gpa"] = students["gpa"].fillna(students["gpa"].median())
students

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          0.0
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0

In [47]:
##Replace missing scholarships with zero
students['scholarship'] = students['scholarship'].fillna(0)
students

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          0.0
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0

In [48]:
##Count students by department
print(students['department'].value_counts())

department
CS    5
IT    3
SE    2
Name: count, dtype: int64

In [50]:
##Count scholarship recipients
recipients = (students['scholarship'] > 0).sum()
print(recipients)

6

In [51]:
##Find the highest GPA
print(students['gpa'].max())

3.9

In [53]:
##Find the lowest GPA
print(students['gpa'].min())

2.9

In [54]:
##Calculate average GPA
print(students['gpa'].mean())

3.4899999999999998

In [55]:
##Calculate total scholarship amount.
print(students['scholarship'].sum())

22500.0